version: 2.1

jobs:
  build:
    docker:
      - image: cimg/base:current
    resource_class: small
    steps:
      - checkout
      - run:
          name: "Building"
          command: ""
  test:
    docker:
      - image: cimg/base:current
    resource_class: small
    steps:
      - checkout
      - run:
          name: "Testing"
          command: ""

workflows:
  datashield_ci:
    jobs:
      - build
      - test
