version: 2.1

jobs:
  build:
    docker:
      - image: cimg/base:current
    resource_class: small
    steps:
      - run: |
          echo "Building"
          echo "  Repo Name: " $CIRCLE_PROJECT_REPONAME
          echo "  Branch:    " $CIRCLE_BRANCH
          echo "  Tag:       " $CIRCLE_TAG
      - run: |
          # Add "R" repo
          sudo apt update -y
          sudo apt upgrade -y
          wget -qO- https://cloud.r-project.org/bin/linux/ubuntu/marutter_pubkey.asc | sudo gpg --dearmor -o /usr/share/keyrings/r-project.gpg
          echo "deb [signed-by=/usr/share/keyrings/r-project.gpg] https://cloud.r-project.org/bin/linux/ubuntu jammy-cran40/" | sudo tee -a /etc/apt/sources.list.d/r-project.list
          sudo apt update -y
      - run: |
          # Install R
          sudo apt upgrade -y
          sudo apt install --no-install-recommends r-base -y
      - run: |
          # Install R
          sudo R
workflows:
  datashield_ci:
    jobs:
      - build
