version: 2.1

jobs:
  build:
    docker:
      - image: cimg/base:current
    steps:
      - checkout
      - run:
          name: "Building"
          command: "echo Building"
  test:
    docker:
      - image: cimg/base:current
    steps:
      - checkout
      - run:
          name: "Testing"
          command: "echo Testing"

workflows:
  build-image-background:
    jobs:
      - build
      - test
