version: 2.1

jobs:
  build:
    docker:
      - image: cimg/base:current
    resource_class: small
    steps:
      - checkout
      - run:
          name: "Building"
          command: "echo 'Building'"
      - run: echo $CIRCLE_BRANCH
      - run: echo $CIRCLE_PROJECT_REPONAME
      - run: echo $CIRCLE_TAG
  test:
    docker:
      - image: cimg/base:current
    resource_class: small
    steps:
      - checkout
      - run:
          name: "Testing"
          command: "echo 'Testing'"

workflows:
  datashield_ci:
    jobs:
      - build
      - test
