version: 2.1

jobs:
  build:
    docker:
      - image: cimg/base:current
    resource_class: small
    steps:
      - run: |
          echo "Building"
          echo "  Repo Name: " $CIRCLE_PROJECT_REPONAME
          echo "  Branch:    " $CIRCLE_BRANCH
          echo "  Tag:       " $CIRCLE_TAG
      - run: |
          # Add "R" repo
          sudo apt update -y
          sudo apt install --no-install-recommends software-properties-common dirmngr
          sudo wget -qO- https://cloud.r-project.org/bin/linux/ubuntu/marutter_pubkey.asc | sudo tee -a /etc/apt/trusted.gpg.d/cran_ubuntu_key.asc
          sudo add-apt-repository "dep https://cloud.r-project.org/bin/linux/ubuntu $(lsb_release -cs)-cran40/"

          # Install R
          sudo apt update -y
          sudo apt upgrade -y
          sudo apt install r-base -y
workflows:
  datashield_ci:
    jobs:
      - build
