version: 2.1

jobs:
  baseclient_base:
    docker:
      - image: cimg/base:current
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD
    resource_class: small
    steps:
      - checkout
      - setup_remote_docker:
          docker_layout_caching: true
      - run:
          name: Display settings
          command: |
            echo "Building"
            echo "  Repo Name: " $CIRCLE_PROJECT_REPONAME
            echo "  Branch:    " $CIRCLE_BRANCH
            echo "  Build Num: " $CIRCLE_BUILD_NUM
            echo "  Tag:       " $CIRCLE_TAG
      - run:
          name: Build and push docker image
          command: |
            TAG=1.0.$CIRCLE_BUILD_NUM
            docker build -t datashield/baseclient-base:$TAG --file BaseClient_Dockerfile .
            echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
            docker push datashield/baseclient-base:$TAG
workflows:
  build:
    jobs:
      - baseclient_base
