version: 2.1

jobs:
  dsclient:
    docker:
      - image: cimg/base:current
    resource_class: small
    steps:
      - checkout
      - setup_remote_docker:
          docker_layout_caching: true
      - run: |
          echo "Building"
          echo "  Repo Name: " $CIRCLE_PROJECT_REPONAME
          echo "  Branch:    " $CIRCLE_BRANCH
          echo "  Tag:       " $CIRCLE_TAG
      - run: |
          TAG=1.0.$CIRCLE_BUILD_NUM
          docker build -t datashield/circleci-dsclient-base:$TAG --file dsClient_Dockerfile .
          echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
          docker push datashield/app:$CIRCLE_BRANCH
workflows:
  dsclient:
    jobs:
      - build
