version: 2.1

jobs:
  build:
    docker:
      - image: cimg/base:current
    resource_class: small
    steps:
      - run: |
          echo "Building"
          echo "  Repo Name: " $CIRCLE_PROJECT_REPONAME
          echo "  Branch:    " $CIRCLE_BRANCH
          echo "  Tag:       " $CIRCLE_TAG
      - run: |
          sudo apt update -y
          sudo apt upgrade -y
          sudo apt install r-base -y
workflows:
  datashield_ci:
    jobs:
      - build
